- README.md
I updated the install dev dependencies in [README.md](https://github.com/es-ude/elastic-ai.creator/blob/0288e04e546dbc91d60884588fe5a31e0f81fa7f/README.md?plain=1#L51-L56), please check.
> docs(readme): fix commands of install dev dependencies

- .github/workflows/main.yml
The installation of dependencies fails during semantic release workflow.
> Fix semantic release

- elasticai/creator/ir/graph_delegate.py
- elasticai/creator/ir/graph_delegate_test.py
- elasticai/creator/ir/graph_iterators.py
- elasticai/creator/ir/humble_base_graph.py
- elasticai/creator/ir/humble_base_graph_test.py
This data structure and its iterators shall reduce complexity
for more advanced graph data structures. It manages nodes/edges
and we can implement different traversals etc. for it.
More advanced graphs can then delegate these operations to the
easier to test delegate.
Please let me know if the term delegate makes sense for you here.
> feat(ir): add graph delegate and iterators

- elasticai/creator/nn/quantized_grads/_math_operations.py
- elasticai/creator/nn/quantized_grads/fixed_point/__init__.py
- elasticai/creator/nn/quantized_grads/fixed_point/_round_to_fixed_point_autograd.py
- elasticai/creator/nn/quantized_grads/fixed_point/_two_complement_fixed_point_config.py
- elasticai/creator/nn/quantized_grads/fixed_point/math_operations.py
- elasticai/creator/nn/quantized_grads/fixed_point/quantize_to_fixed_point.py
- elasticai/creator/nn/quantized_grads/fixed_point/test_quantize_to_fixed_point.py
- elasticai/creator/nn/quantized_grads/quantize.py
- tests/system_tests/helper/test_parse_tensors_to_bytearray.py
This feature adds basic support for future use of quantized fixed point gradients. It includes a refactor of the existing a new  fixed point config which is refactored because the old one was doing to much. Following, I changed the naming a bit and have now a fixed point configuration with datafields only. The quantization function is now moved to the quantize_to_fixed_point file using the fixed point configuration.
> 400 add math ops and refactored fixed point config

- .envrc
- CONTRIBUTION.md
- devenv.lock
- devenv.nix
- devenv.yaml
- devenv_modules/ghdl/devenv.nix
This commit allows to automatically setup
a dev environment with all necessary dependencies
installed. It should work cross-platform on
* macos
* linux
* wsl
The current setup automatically installs
the rosetta version of ghdl on mac m1.
You can install `direnv` to automatically
load that environment on entering the shell.
> chore: add basic support for devenv

- elasticai/creator/plugin.py
- tests/unit/plugin_test.py
Previously trying to instantiate a `Plugin` from
a dictionary just passed or failed with a hard
to parse error message from a call to inspect.Signature.bind 
Now we analyse expected and actual parameters
and raise more meaningful error when there is
an unexpected parameter in the loaded config.
> feat: improve error handling when loading plugins

- elasticai/creator/utils/ghdl_msg.py
- elasticai/creator/utils/hw_test_runner.py
- pyproject.toml
- tests/unit/utils/hw_test_runner_test.py
The change should help separate easier to test
ghdl message parsing and building from the
actual test runner and renderer, that rely
heavily on the interaction with ghdl
and checking the output.
> refactor(utils): move ghdl_msg parsing to its own module

- elasticai/creator/nn/quantized_grads/fixed_point/quantize_to_fixed_point.py
- elasticai/creator/nn/quantized_grads/fixed_point/test_quantize_to_fixed_point.py
- elasticai/creator/nn/quantized_grads/fixed_point/test_two_complement_fixed_point_config.py
- elasticai/creator/nn/quantized_grads/fixed_point/two_complement_fixed_point_config.py
Since the device of each tensor needs to be the same to perform operations, we need to make sure, that the fixedpointconfigs values can be set on the device. Thus, the device needs to be to the fixed point configuration.
However, when using 
```python 
@property
def minimum_as_rational_tensor(self):
return torch.Tensor([self.minimum_as_rational]).to(self.device)
```
two problems occure. 
1. The tensor is transferred to the device every time the value is called.
2. The value self.minimum_as_rational is called every time which includes multiple computations.
Ideally, every value is computed just once and then is referred to. Unfortunatly, python dataclasses can not compute something once. Also, computing something during post_init is not possible, because the dataclass is frozen and does …
> feat(qgrads): add support for execution on specific devices

- pyproject.toml
- uv.lock
Uses the hatch-vcs plugin to dynamically inject
the package version from the latest git tag
matching 'v*'. Additionally, the plugin will
create pre-release suffixes based on git history
and timestamp.
Changing the version field manually was a source
for errors. Now, there is a single source for
the version, the tag.
You can call `hatch version` to find out about
the current package version.
> build: use git to dynamically extract version

- .gitignore
- devenv.nix
- devenv_modules/ghdl/Readme.adoc
- devenv_modules/ghdl/devenv.nix
- docs/modules/ROOT/examples/devenv.local.with-cuda.nix
The ghdl devenv submodule can now provide vivado.
This is mostly useful on nixos systems, where
it represents basically the only way to make
vivado available. Therefore it is disabled
by default.
Additionally the inclusion of ghdl can be turned
of now in your devenv.local.nix by setting
languages.vhdl.enable = false;
> chore(devenv): support vivado and add options to ghdl module

- docs/supplemental-ui/partials/header-content.hbs
Added a GitHub repository link in the navigation bar of the documentation header (`header-content.hbs`)  
to improve accessibility and provide an easy way for users to navigate to the project repository.
fixes #504
> docs: add GitHub repository link to documentation header

- elasticai/creator/vhdl/skeleton_id.py
Discovering vhdl files in the build folder would
fail in cases of nested folders. The function
now recursively walks through dirs and computes
hashes only on files and ignores folders.
> fix(skeleton_id): properly deal with nested folders

- elasticai/creator/ir/graph.py
- elasticai/creator/ir2vhdl.py
The change should make the public interface
of the ir package easier and cleaner.
The functions in `ir.graph_iterators`
are not exported via __init__.py,
which defines the public ir interface
now.
> refactor(ir): add iterator methods to ir.Graph

- devenv.nix
- pyproject.toml
- tach.toml
- uv.lock
Python's lack of visibility modifiers
makes it increasingly difficult to respect
architectural boundaries. `tach` wants to fix
that by checking imports and linting all
dependencies that
* have not been explicitly declared
* are violating public interface constraints
I expect that we'll have to tweak the tach.toml
file as the architecture matures.
> chore: use tach to adhere to architecture

- docs/conf.py
- elasticai/creator/ir/graph.py
- elasticai/creator/ir2vhdl/ir2vhdl.py
- tests/unit_tests/ir/graph_test.py
- tests/unit_tests/ir/ir_data_graph_test.py
- tests/unit_tests/ir2vhd_test.py
The change makes the ir.Graph type more usable
out of the box.
Most importantly serialization/deserialization
routines can be used for subclasses as well.
Disadvantages:
* cannot inherit from ABC at the same time
* stronger coupling to IrData as this is package internal I do not consider this to be a big drawback
Advantages:
* easier access to custom attributes (see IrData)
* a common serialization/deserialization routine for all subclasses
* encourages composition instead of inheritance for uses beyond adding custom attribute fields
* increased consistency in the ir package as all exported types are now based on IrData
* Closes: #530
BREAKING CHANGE: Might break clients that were using `asdict` `fromdict` methods of `ir2vhdl.Implementation` previously. Clients using the old version of …
> feat(ir): turn ir.Graph into a IrData object

- docs/apidocs/elasticai.creator/elasticai.creator.ir2vhdl.testing.md
- docs/apidocs/elasticai.creator/elasticai.creator.ir2vhdl.testing.testing.md
- docs/apidocs/elasticai.creator_plugins.counter/elasticai.creator_plugins.counter.md
- docs/apidocs/index.rst
- docs/creator/index.md
- docs/creator/plugins/counter.md
- docs/creator/plugins/index.md
- elasticai/creator/ir2vhdl/testing/__init__.py
- elasticai/creator/ir2vhdl/testing/testing.py
- elasticai/creator_plugins/counter/README.md
- elasticai/creator_plugins/counter/__init__.py
- elasticai/creator_plugins/counter/docs/antora.yml
- elasticai/creator_plugins/counter/meta.toml
- elasticai/creator_plugins/counter/tests/counter_tb.vhd
- elasticai/creator_plugins/counter/tests/run_tbs.py
- elasticai/creator_plugins/counter/vhdl/counter.vhd
Adds a simple counter design. You can
set a maximum value as a generic
parameter. Counter will reset to 0
after reaching the maximum.
The component will be used,
e.g., to implement filters
with stride higher than one
and to find out if a buffer
has been filled with valid
data.
> feat(vhdl-plugins): add counter

- elasticai/creator/ir/__init__.py
- elasticai/creator/ir/required_field.py
- tests/unit_tests/ir/ir_data_test.py
Introduces decorators to define instance methods
as required fields. The advantage is two-fold:
1. The method's type annotations are used to infer the types of the resulting descriptor. This should often be more intuitive than the somewhat lengthy type annotations that were necessary previously.
2. get_convert functions can now access the owning instances state.
For now, we specifically disallow accessing the instances state from writeable field converters as the chance for inconsistencies seems to be too high.
> feat(ir): support decorating methods as required fields

- elasticai/creator/ir2torch/ir2torch.py
- elasticai/creator/torch2ir/torch2ir.py
- tests/integration_tests/plugin_integ_test.py
- tests/unit_tests/ir2torch_test.py
- tests/unit_tests/torch2ir_test.py
Pytorch tracing will eliminate duplicate submodules and replace them by a single unique object.
When trying to load state dicts generated from
modules with duplicate submodules, that would lead to errors where the values referring to duplicates will miss a corresponding submodule in the result
of the ir2torch conversion.
This commit introduces a feature that will strip
the state dict of all keys not present in an
implementation registry before loading the
state dict. Thus avoiding the problem mentioned
above.
> feat(ir2torch): support loading model state dicts

- devenv.nix
- docs/apidocs/elasticai.creator/elasticai.creator.md
- docs/apidocs/elasticai.creator/elasticai.creator.torch2ir.core.md
- docs/apidocs/elasticai.creator/elasticai.creator.torch2ir.default_module_handlers.md
- docs/apidocs/elasticai.creator/elasticai.creator.torch2ir.md
- docs/apidocs/elasticai.creator/elasticai.creator.torch2ir.torch2ir.md
- elasticai/creator/torch2ir/__init__.py
- elasticai/creator/torch2ir/core.py
- elasticai/creator/torch2ir/default_module_handlers.py
- elasticai/creator/torch2ir/torch2ir.py
- tach.toml
- tests/unit_tests/torch2ir_test.py
* converts pytorch models to ir including hyper parameters
* model state still has to be saved and loaded to/from dict via pytorch.
> feat(torch2ir): support simple torch 2 ir conversion w/o model state

- .gitignore
- devenv.nix
- docs/apidocs/elasticai.creator/elasticai.creator.ir2torch.default_handlers.md
- docs/apidocs/elasticai.creator/elasticai.creator.ir2torch.ir2torch.md
- docs/apidocs/elasticai.creator/elasticai.creator.ir2torch.md
- docs/apidocs/elasticai.creator/elasticai.creator.md
- elasticai/creator/ir2torch/__init__.py
- elasticai/creator/ir2torch/default_handlers.py
- elasticai/creator/ir2torch/ir2torch.py
- pyproject.toml
- tests/unit_tests/ir2torch_test.py
- uv.lock
The Ir2Torch class can be used to translate from
our IR to pytorch. The commit adds support for
linear and relu. Support for other types can
be added by adding the corresponding handlers
to `elasticai.creator.ir2torch.default_handlers`
> feat(ir2torch): add Ir2Torch and support linear+relu

- pyproject.toml
Now that we're using hypothesis there will be
tests that do not depend on hardware, but will
just run for quite long.
Those should be marked with 'slow'.
Opposed to 'simulation', 'slow' does not imply
dependence on hw simulation tools.
> chore(pytest): add new 'slow' marker

- elasticai/creator/ir/graph.py
This allows for easier comparison, especially in unit tests.
> feat(ir): implement __eq__ for nodes/edges attributes of Graphs

- elasticai/creator/ir/ir_data.py
Printing the __class__ attribute directly was
hard to parse in test outputs.
Just printing the name is shorter and easier to read.
> chore(ir): print class name in instead of class in IrData repr

- pyproject.toml
Configures mypy, so we can gradually improve
type annotations. The most important part is
to not add more inconsistencies. This config
should ensure that.
> chore(build): configure mypy

- elasticai/creator/ir/graph.py
- tests/unit_tests/ir/graph_test.py
Previously the attributes `nodes` and `edges` for
graphs were properties that would build a mapping
for nodes and edges using user provided `node_fn`
and `edge_fn`. Since the commit that made 
`Graph` an `IrData` class as well, this leads
to an inconsistency:
We know that `"nodes"` and `"edges"` are
in each graphs data dict and we expect
them to be in there. But contrary to the
intent of the IrData class (which `Graph`)
inherits from, these two fields are not
registered as required fields.
Even though it's not a problem atm, it
is still a liskov violation.
> refactor(ir): expose nodes/edges via ir data fields

- elasticai/creator/ir/__init__.py
- elasticai/creator/ir/graph.py
- elasticai/creator/ir/graph_rewriting.py
- elasticai/creator/ir/name_generation.py
- tests/unit_tests/ir/graph_transforms/rewrite_test.py
- tests/unit_tests/ir/graph_transforms/subgraph_matching_test.py
- tests/unit_tests/ir/graph_transforms/utils.py
- tests/unit_tests/ir/name_generation_test.py
Adds an algorithm loosely based on double push out method for graph rewriting.
This `GraphRewriter` allows to replace the first
found occurence of a given pattern in a graph
by a replacement pattern.
It will perform automatic renaming in case of
naming collisions.
> feat(ir): support pattern based graph rewriting

- docs/conf.py
- pyproject.toml
- uv.lock
This allows to draw more complex diagrams
other than mermaid. In this case it is
added to specifically support drawing
wavedrom diagrams of waveforms.
> chore(pyproject): add wavedrom sphinx extension

- elasticai/creator/ir2vhdl/testing/testing.py
This allows to call specific `run_tbs.py` scripts
with command line args. E.g., to open the wave
form viewer for the test run.
Signed-off-by: Lukas Einhaus <lukas.einhaus@uni-due.de>
> test(vhdl): pass command line args to vunit test facade

- .github/workflows/release.yaml
- docs/creator/plugins/index.md
- docs/creator/plugins/lutron.md
- elasticai/creator_plugins/lutron/README.md
- elasticai/creator_plugins/lutron/__init__.py
- elasticai/creator_plugins/lutron/language.py
- elasticai/creator_plugins/lutron/lutron.py
- elasticai/creator_plugins/lutron/meta.toml
- elasticai/creator_plugins/lutron/tests/test_lutron.py
- tach.toml
A lutron represents a precomputed LUT-based
neuron. This commit adds a plugin that
will automatically generate the hw design
from a given truth table.
> feat(vhdl-plugins): add lutron implementation

- docs/creator/plugins/combinatorial.md
- docs/creator/plugins/index.md
- elasticai/creator/ir2vhdl/ir2vhdl.py
- elasticai/creator_plugins/combinatorial/README.md
- elasticai/creator_plugins/combinatorial/__init__.py
- elasticai/creator_plugins/combinatorial/clocked_combinatorial.py
- elasticai/creator_plugins/combinatorial/combinatorial.py
- elasticai/creator_plugins/combinatorial/language.py
- elasticai/creator_plugins/combinatorial/meta.toml
- elasticai/creator_plugins/combinatorial/tests/shift_register_test.py
- elasticai/creator_plugins/combinatorial/tests/striding_shift_register_test.py
- elasticai/creator_plugins/combinatorial/tests/test_vhdl_implementation.py
- elasticai/creator_plugins/combinatorial/tests/test_vhdl_nodes.py
- elasticai/creator_plugins/combinatorial/tests/wiring_test.py
- elasticai/creator_plugins/combinatorial/unclocked_combinatorial.py
- elasticai/creator_plugins/combinatorial/vhdl_nodes/__init__.py
- elasticai/creator_plugins/combinatorial/vhdl_nodes/clocked_combinatorial.py
- elasticai/creator_plugins/combinatorial/vhdl_nodes/node_factory.py
- elasticai/creator_plugins/combinatorial/vhdl_nodes/shift_register.py
- elasticai/creator_plugins/combinatorial/vhdl_nodes/sliding_window.py
- elasticai/creator_plugins/combinatorial/vhdl_nodes/striding_shift_register.py
- elasticai/creator_plugins/combinatorial/vhdl_nodes/unclocked_combinatorial.py
- elasticai/creator_plugins/combinatorial/vhdl_nodes/vhdl_node_wrapper.py
- elasticai/creator_plugins/combinatorial/wiring.py
- tach.toml
The plugin allows to automatically combine existing components, that implement one of
two axi like interfaces (clocked/unclocked), based on a given IR graph.
Closes: #416
> feat(vhdl-plugins): add combinatorial components

- elasticai/creator/graph/graph_rewriting.py
- tests/unit_tests/graph/rewrite_test.py
- tests/unit_tests/graph/utils.py
There is no real advantage to functions over mappings. In many cases we can just pass plain dicts which are easier to construct than functions and mappings allow us to reason about domain and image (keys and values).
> refactor(graph): use mappings instead of functions for lhs/rhs

- elasticai/creator/graph/__init__.py
- elasticai/creator/graph/graph.py
- elasticai/creator/graph/graph_rewriting.py
- elasticai/creator_plugins/time_multiplexed_sequential/tests/test_lower_fn_with_sliding_window_input.py
- tests/unit_tests/graph/graph_test.py
- tests/unit_tests/graph/rewrite_test.py
- tests/unit_tests/graph/utils.py
- tests/unit_tests/torch2ir_test.py
The graph rewriting feature was only the first step in what we need to transform ir implementations.
The graph rewrite will take care of matching
subgraphs to a pattern and replacing them by a
new graph.
Usually though, the metadata in the resulting
replacement subgraph depends on the original
(replaced) subgraph. E.g., you might want
to keep parameters of a convolution, while
changing the parameters of a batchnorm
and removing the activation function.
Therefore the graph rewriter now provides
access to the replaced, the resulting and
the interface subgraphs, such that we can
fill in the parameters after a subgraph
has been replaced. This keeps the code
for adjusting parameters separate from
the graph rewriter itself.
> feat(graph): provide replaced and resulting subgraph from rewriting

- elasticai/creator/graph/graph_rewriting.py
- elasticai/creator/graph/subgraph_matching.py
- tests/unit_tests/graph/utils.py
The arguments tend to be of same type and
making a mistake with their order in find_subgraph or graph rewriting can lead to annoying errors.
Therefore most of the involved functions now
require kw arguments.
> refactor(graph): make pattern/graph args kw only

- .gitignore
- docs/creator/ir.md
- elasticai/creator/graph/__init__.py
- elasticai/creator/graph/base_graph.py
- elasticai/creator/graph/graph.py
- elasticai/creator/graph/graph_rewriting.py
- elasticai/creator/graph/subgraph_matching.py
- elasticai/creator/ir/__init__.py
- elasticai/creator/ir/base/ir_data.py
- elasticai/creator/ir/core/__init__.py
- elasticai/creator/ir/core/implementation.py
- elasticai/creator/ir2vhdl/ir2vhdl.py
- elasticai/creator/ir_transforms/__init__.py
- elasticai/creator/ir_transforms/reorder.py
- elasticai/creator/torch2ir/core.py
- elasticai/creator/torch2ir/torch2ir.py
- pyproject.toml
- tach.toml
- tests/unit_tests/graph/graph_test.py
- tests/unit_tests/graph/utils.py
- tests/unit_tests/ir/implementation_test.py
- tests/unit_tests/ir/ir_data_graph_test.py
- tests/unit_tests/ir2vhd_test.py
- tests/unit_tests/ir_transforms/reorder_test.py
- uv.lock
Introduces a SequentialReorderer that uses the graph
rewriter and ir.Implementation to create new graphs
where a given pattern is reordered as specified
by the client. All data from the old graph (including
node data) will be copied to the new graph.
This is essential for many optimizations we want
to perform, before or while going down to low level ir.
> feat(ir_transform): support reordering of sequential subgraphs

- elasticai/creator/ir2verilog/templates.py
- elasticai/creator/ir2vhdl/__init__.py
- elasticai/creator/ir2vhdl/vhdl_template.py
- elasticai/creator/template.py
- tests/unit_tests/ir2verilog_test.py
This allows clients to decide on their own how
the parameters in the template have to be replaced. E.g., in verilog the default delimiter `$` is
a language token. Having clients wrap the string
in a template object makes modifications like this one trivial.
Closes #607
> fix(template)!: return str instead of str.Template from builder

- elasticai/creator/ir2verilog/templates.py
- tests/unit_tests/ir2verilog_test.py
> fix(verilog): update verilog templates to correctly replace arrays

- elasticai/creator/graph/__init__.py
- elasticai/creator/graph/subgraph_matching.py
- elasticai/creator/graph/vf2/__init__.py
- elasticai/creator/graph/vf2/matching.py
- elasticai/creator/ir_transforms/reorder.py
- tests/unit_tests/graph/utils.py
- tests/unit_tests/graph/vf2/match_test.py
In most cases we want to find/replace all
non-overlapping subgraphs specified by a
given pattern. This extends the vf2 based
algorithm to find all occurences of the
pattern instead of just the first one.
> feat(graph): find all non-overlapping subgraphs

- elasticai/creator/graph/__init__.py
- elasticai/creator/graph/graph_iterators.py
- elasticai/creator_plugins/time_multiplexed_sequential/src/__init__.py
- tests/unit_tests/graph/graph_test.py
Pre/In/Postorder traversal makes no sense in the
context of general graphs instead of trees.
Additionally the commit extends the test cases
to make the dfs more explicit and make it easier
to narrow down problems.
> refactor(graph): rename dfs_preorder to dfs_iter

- elasticai/creator/graph/graph_rewriting.py
- elasticai/creator/ir_transforms/reorder.py
- tests/unit_tests/graph/utils.py
The rewrite algorithm cannot and does not need to
handle multiple matches. It should be up to
the caller to decide how each match should be
handled in case of multiple ones. 
This deprecates using functions that return
multiple matches as matchers for the graph rewriter.
> refactor(graph): only require a single match in rewriter

- elasticai/creator/graph/__init__.py
- elasticai/creator/graph/graph_rewriting.py
- tests/unit_tests/graph/rewrite_test.py
This rewrite function is a little bit 
more low level than the previously
introduced GraphWriter class.
It operates only on very basic
datastructures (dicts, and graph.Graph).
Instead of injecting a match function,
users just provide the match as a
dict. Ie., opposed to GraphWriter
the new function will not call
other functions. Instead the user
has to perform the matching step
by themselves and pass the match
dict to the `rewrite` call.
This makes it easier to perform
a rewrite on multiple matches.
> refactor(graph): add rewrite function

- elasticai/creator/graph/__init__.py
- elasticai/creator/graph/graph_rewriting.py
- tests/unit_tests/graph/dangling_edges_test.py
We only want to rewrite non-overlapping matches,
where the rewrite would not produce dangling
references. The filter function will only
return the subgraph matches that fulfill this
condition.
> feat(graph): filter subgraph matches for rewrite

- elasticai/creator/graph/graph_rewriting.py
- tests/unit_tests/graph/rewrite_test.py
The interface is already implicitly defined by specifying the left and right hand side mapping from interface nodes to pattern and replacement respectively.
Passing an additional interface graph, would make the API overly complex and add boilerplate code for
building the interface graph.
> refactor(graph): remove interface arg from rewrite function

- elasticai/creator/graph/graph_rewriting.py
- elasticai/creator/ir_transforms/reorder.py
- tests/unit_tests/graph/rewrite_test.py
- tests/unit_tests/graph/utils.py
GraphRewriter was deprecated previously.
> refactor(graph): use simpler rewrite function instead of GraphRewriter

- elasticai/creator/ir/core/implementation.py
- elasticai/creator/ir_transforms/__init__.py
- elasticai/creator/ir_transforms/move_to_submodules.py
- elasticai/creator/torch2ir/__init__.py
- tests/integration_tests/ir_transforms/move_to_subimpls_test.py
Adds a function that will replace every occurence of a pattern by a single node and move the pattern to a dedicated implementation automatically.
> feat(ir_transforms): extract patterns into sub implementations

- CHANGELOG.md
- docs/creator/ir.md
- elasticai/creator/graph/graph_rewriting.py
- elasticai/creator/ir2torch/ir2torch.py
- ir_spec/conv1d.schema.json
- tests/unit_tests/ir2torch_test.py
- tests/unit_tests/torch2ir_test.py
Previously we would not be able to reassemble
a model that was build like this
m = Sequential(Sequential(ReLU()))
because the nested modules name would have been
"_0._0". Ir2Torch would try to reuse that name
when reassembling the model, but torch
does not allow "." in module names.
This commit recreates the original
module hierarchy by combining nn.Module
containers with the torch.fx.Graph.
> feat(ir2torch): support nested module hierarchies

- elasticai/creator_plugins/combinatorial/README.md
- elasticai/creator_plugins/counter/README.md
- elasticai/creator_plugins/grouped_filter/README.md
- elasticai/creator_plugins/lutron/README.md
- elasticai/creator_plugins/padding/README.md
- elasticai/creator_plugins/shift_register/README.md
- elasticai/creator_plugins/skeleton/README.md
- elasticai/creator_plugins/sliding_window/README.md
- elasticai/creator_plugins/striding_shift_register/README.md
- elasticai/creator_plugins/time_multiplexed_sequential/README.md
Not explicitly stating what stage of the
translation process a plugin is meant for
made it hard to put each of them into context.
Adding that information now, to make it
easier to reason about how/when to use each
of the plugins.
> docs(plugins): name plugin translation stages

- elasticai/creator/graph/__init__.py
The protocol was introduced to ensure that clients implementing new constraints will use the correct
order for pattern and graph nodes in call signature. This is expected to be a source for errors as both arguments will typically be of the same type.
Hence, the protocol should have been exposed already.
> refactor(graph): publicly expose NodeConstraintFn protocol

- docs/creator/plugin-system.md
- elasticai/creator/plugin.py
Explicitly state that the plugin system is used
to extend translation passes.
> docs(plugins): clarify purpose of the plugin system

- elasticai/creator/graph/vf2/matching.py
- elasticai/creator/graph/vf2/state.py
- tests/unit_tests/graph/vf2/match_test.py
To prevent exploring duplicate states in the state space representation a total order on nodes was
established. Source of the bug was that this
order was computed over the partial state space
while it should have been computed over the current candidate pairs.
> fix(graph): fix bug that was preventing matches in some edge cases

- elasticai/creator/ir/rewriting/rewriter.py
If a user does not specify an init routine for a replacement node the rewriter would just fail with a KeyError not mentioning the nodes name. This turns the error into a ValueError and communicates the node name in the message. This way, users can ensure to provide
an init routine for the mentioned node.
> fix(ir): improve error message when initializer is not found

- elasticai/creator_plugins/skeleton/README.md
Documentation was previously almost exclusively talking about the buffered network wrapper.
> docs(skeleton): add explanation for skeleton generics/padding and example

- .github/actions/prepare-devenv/action.yml
- .github/workflows/checks.yml
- .github/workflows/docs.yml
- devenv.lock
- devenv.yaml
- devenv_modules/ghdl/devenv.nix
- elasticai/creator/ir_transforms/reorder.py
- pyproject.toml
- tests/system_tests/conv1d/conv1d.py
- tests/system_tests/linear_layer/linear_layer.py
Points devenv to current release on nixos-25.05 branch.
Currently this is devenv 1.8.1.
Also, we apply the new --mode flag to use the
tasks in a `make` like fashion as we did before.
(The behaviour for executing tasks was changed in 1.7)
And we apply minor changes to ruff setup to make
newer python syntax pass, e.g. match case statements.
- **chore(gh-actions): update devenv version for ci to point to nixos-25.05**
- **style: reorder imports**
- **fix(devenv): pin ghdl to version from nixpkgs-24.11**
- **chore(gh-actions): call devenv with --mode before flag to execute deps**
- **chore(pyproject): use py311 for ruff checks**
> update and fix ci

- elasticai/creator/ir/rewriting/rewriter.py
- tests/unit_tests/ir/rewriting/rewriting_test.py
The rewrite algorithm found all possible matches
and would then edit the corresponding subgraphs.
However, this method would edit nodes that might
have been removed/edited already.
The graph module provides methods to filter
matches to obtain only non-overlapping matches
that are safe for rewrite.
The ir.rewrite module now uses that function
before applying the rewrite rules to matches.
> fix(ir): remove problematic matches before rewriting

- elasticai/creator/ir2torch/ir2torch.py
- elasticai/creator/torch2ir/torch2ir.py
- tests/unit_tests/ir2torch_test.py
Misunderstood torch fx api. To make nodes depend
on other nodes, we have to pass the node objects
instead of just their names.
Using the names, will result in the executed
code calling the targets with strings.
> fix(ir2torch): fix argument passing for torch fx nodes

- elasticai/creator/ir2vhdl/ir2vhdl.py
- elasticai/creator_plugins/combinatorial/tests/test_vhdl_nodes.py
- elasticai/creator_plugins/combinatorial/vhdl_nodes/shift_register.py
- elasticai/creator_plugins/combinatorial/vhdl_nodes/sliding_window.py
- elasticai/creator_plugins/combinatorial/vhdl_nodes/striding_shift_register.py
Implementation would previously incorrectly return
depth instead of width (and set width to 1)
in cases where only width was specified
> fix(ir2vhdl): use correct width for Shape

- elasticai/creator_plugins/combinatorial/clocked_combinatorial.py
- elasticai/creator_plugins/combinatorial/tests/clock_tree_test.py
The valid_in/valid_out signals would not be connected at all times
previously. This was for two reasons:
1. Identification of clocked components not working correctly
2. iterating over nodes top to bottom instead of bottom to top
Both has been fixed and a corresponding test has been added.
> fix(combinatorialplugin): connect valid_in/out signals correctly

- pyproject.toml
- uv.lock
Pyserial is often used to communicate with
the embedded systems via UART.
> chore(pyproject): add pyserial as a dependency

- elasticai/creator/testing/__init__.py
- elasticai/creator/testing/cocotb_pytest.py
- tests/integration_tests/cocotb_pytest/test/cocotb_pytest_test.py
- tests/integration_tests/cocotb_pytest/vhdl/my_testbench.vhd
- tests/unit_tests/testing/cocotb_pytest_test.py
The goal is to provide a convenient solution to
inject parameters into a cocotb test from its
corresponding pytest test runner.
This is especially useful in scenarios, where
the generated hdl code  and its test depend on the
same python parameters, verilog parameters
or vhdl generics.
> feat(testing): introduce cocotb_test_fixture

- elasticai/creator/testing/cocotb_pytest.py
- tests/unit_tests/testing/cocotb_pytest_test.py
When parametrizing cocotb test runners with arguments that are
non primitive, we want to avoid super long folder names, hence
we use hashes to encode list and dict like argument values.
> feat(cocotb): use hash for generating test data paths based on lists etc
