es-ude/elastic-ai.creator

elasticai/creator/precomputation.py
elasticai/creator/tags_utils.py
elasticai/creator/tests/test_precomputation.py

Serialize precomputations as json

---

.gitignore
elasticai/creator/examples/parametrize_convolution.py
elasticai/creator/layers.py
elasticai/creator/tests/test_layer.py
elasticai/creator/tests/test_precomputation.py
poetry.lock
pyproject.toml

use parametrization in favor of our previous custom layers
see https://pytorch.org/docs/master/generated/torch.nn.utils.parametrize.register_parametrization.html#torch.nn.utils.parametrize.register_parametrization
closes  #7

Torch parametrizations

---

elasticai/creator/tests/vhdl/test_generate_sigmoid_vhd.py
elasticai/creator/tests/vhdl/test_generate_tanh_vhd.py
elasticai/creator/tests/vhdl/test_precomputed_scalar_function_process.py
elasticai/creator/tests/vhdl/vhdl_file_testcase.py
elasticai/creator/vhdl/generator/component.py
elasticai/creator/vhdl/generator/functions/generate_sigmoid_vhd.py
elasticai/creator/vhdl/generator/functions/generate_tanh_vhd.py
elasticai/creator/vhdl/generator/generator_functions.py
elasticai/creator/vhdl/generator/precomputed_scalar_function.py
elasticai/creator/vhdl/generator/testbench_strings.py
elasticai/creator/vhdl/language.py
poetry.lock

merge tanh and sigmoid process

---

elasticai/creator/systemTests/models_definition.py
elasticai/creator/systemTests/test_brevitas_representation.py
elasticai/creator/systemTests/test_input.py

remove weight definition

---

elasticai/creator/tests/vhdl/test_generate_sigmoid_vhd.py
elasticai/creator/tests/vhdl/test_generate_tanh_vhd.py
elasticai/creator/tests/vhdl/test_language.py
elasticai/creator/vhdl/generator/precomputed_scalar_function.py
elasticai/creator/vhdl/generator/vhd_strings.py
elasticai/creator/vhdl/language.py

closes #28 
Edit: just saw that the Architecture class is also implemented in Rodrigos pull request #30

first draft of using codegenerators in __call__ of precomputed_scalar_functions

---

elasticai/creator/tests/vhdl/test_generate_sigmoid_vhd.py
elasticai/creator/tests/vhdl/test_generate_tanh_vhd.py
elasticai/creator/tests/vhdl/test_language.py
elasticai/creator/tests/vhdl/test_precomputed_scalar_function_process.py
elasticai/creator/vhdl/generator/functions/generate_mac_async_vhd.py
elasticai/creator/vhdl/generator/generator_functions.py
elasticai/creator/vhdl/generator/precomputed_scalar_function.py
elasticai/creator/vhdl/language.py

Remove line breaks

---

elasticai/creator/systemTests/lstm_cell.py

include chaos lstm cell example

---

elasticai/creator/tests/vhdl/test_number_representations.py
elasticai/creator/vhdl/number_representations.py

closes #97 
Additionally the attribute and method names in the ToLogicEncoder have been improved.

Logic encoder batches

---

elasticai/creator/tests/vhdl/test_number_representations.py
elasticai/creator/vhdl/number_representations.py

92 create tests for the  int to bin str function

---

elasticai/creator/qat/functional.py

new version avoids creating new
tensors in favor of implicit
broadcasts and is more readable

fix(qat): reimplement binarize

---

elasticai/creator/examples/translate_linear_model.py
elasticai/creator/tests/vhdl/components/test_fp_relu_component.py
elasticai/creator/tests/vhdl/translator/abstract/layers/test_fp_relu_module.py
elasticai/creator/tests/vhdl/translator/pytorch/build_functions/test_fp_relu_build_function.py
elasticai/creator/vhdl/components/fp_relu_component.py
elasticai/creator/vhdl/templates/fp_relu.tpl.vhd
elasticai/creator/vhdl/translator/abstract/layers/fp_relu_module.py
elasticai/creator/vhdl/translator/pytorch/build_function_mappings.py
elasticai/creator/vhdl/translator/pytorch/build_functions/__init__.py
elasticai/creator/vhdl/translator/pytorch/build_functions/fp_relu_build_function.py

@julianhoever I think I have achieved this issue (#164), please review my changes.
I basically did is,
1. add the fixed point relu support to the creator.
2. add three tests as unittest
3. create default build mapping for both relu and hard_sigmoid
4. changed the example file a little to check if the default build mapping works
resolve #164

164 add fixed point relu translation

---

elasticai/creator/examples/translate_linear_model.py
elasticai/creator/tests/vhdl/components/test_fp_hard_sigmoid_component.py
elasticai/creator/tests/vhdl/components/test_fp_linear_1d_component.py
elasticai/creator/tests/vhdl/components/test_fp_relu_component.py
elasticai/creator/tests/vhdl/translator/abstract/layers/test_fp_hard_sigmoid_module.py
elasticai/creator/tests/vhdl/translator/abstract/layers/test_fp_relu_module.py
elasticai/creator/vhdl/components/fp_hard_sigmoid_componet.py
elasticai/creator/vhdl/components/fp_relu_component.py
elasticai/creator/vhdl/templates/fp_hard_sigmoid.tpl.vhd
elasticai/creator/vhdl/templates/fp_linear_1d.tpl.vhd
elasticai/creator/vhdl/templates/fp_relu.tpl.vhd
elasticai/creator/vhdl/translator/abstract/layers/fp_hard_sigmoid_module.py
elasticai/creator/vhdl/translator/abstract/layers/fp_relu_module.py
elasticai/creator/vhdl/translator/pytorch/build_functions/fp_hard_sigmoid_build_function.py
elasticai/creator/vhdl/translator/pytorch/build_functions/fp_relu_build_function.py

157 translate simple linear model

---

elasticai/creator/tests/unit/nn/test_lstm.py
elasticai/creator/tests/unit/vhdl/components/test_fp_linear_1d_component.py
elasticai/creator/vhdl/templates/fp_linear_1d.tpl.vhd

only changed the vhdl template, fixed unittest related to lines of this template.

fix(template): linear layer template

---

.pre-commit-config.yaml
elasticai/creator/tests/unit/vhdl/translator/abstract/layers/test_lstm_module.py
elasticai/creator/vhdl/code_files/rom_component.py
elasticai/creator/vhdl/translator/abstract/layers/fp_linear_1d_module.py

resolve #213
@julianhoever to commit, I had to update the `.pre-commit-config.yaml`. I am not sure if I am allowed to do such a thing

213 remove duplicated suffix from linear rom components

---

elasticai/creator/base_modules/arithmetics/float_arithmetics.py
elasticai/creator/base_modules/autograd_functions/round_to_float.py
tests/base_modules/autograd_functions/test_round_to_float.py

This pull request was created to test if the semantic release workflow works correctly. See #285

Rename float autograd function

---

.github/workflows/main.yml

Just adding some debug messages to tackle the problem...

Fix semantic release

---

poetry.lock

resolves:
- https://github.com/es-ude/elastic-ai.creator/security/dependabot/27
- https://github.com/es-ude/elastic-ai.creator/security/dependabot/28
- https://github.com/es-ude/elastic-ai.creator/security/dependabot/26

fix: update deps to resolve security issues

---

elasticai/creator/vhdl/system_integrations/README.md
elasticai/creator/vhdl/system_integrations/firmware_env5.py
elasticai/creator/vhdl/system_integrations/firmware_env5_test.py
elasticai/creator/vhdl/system_integrations/skeleton/network_skeleton_v2.tpl.vhd
elasticai/creator/vhdl/system_integrations/skeleton/skeleton.py

Skeleton v2

---

.github/actions/setup_test_environment/action.yml
elasticai/creator/file_generation/template.py
elasticai/creator/nn/fixed_point/precomputed/precomputed_module.py
elasticai/creator/nn/fixed_point/precomputed/precomputed_module_test.py
elasticai/creator/vhdl/shared_designs/precomputed_scalar_function/design.py
elasticai/creator/vhdl/shared_designs/precomputed_scalar_function/precomputed_scalar_function.tpl.vhd
poetry.lock
pyproject.toml

Reverts es-ude/elastic-ai.creator#349

Revert "Merging main to develop"

---

elasticai/creator/vhdl/system_integrations/top/env5_reconfig_top.vhd

It is not used anywhere so should have no effect

fix(vhdl): #374 remove unnecessary data_buf from top module. 

---

elasticai/creator/ir/core.py
elasticai/creator/ir/graph.py
elasticai/creator/ir/graph_delegate.py
elasticai/creator/ir/graph_iterators.py
elasticai/creator/ir/graph_test.py
elasticai/creator/ir/ir_data.py
elasticai/creator/ir/ir_data_meta.py
elasticai/creator/ir/ir_data_test.py
elasticai/creator/ir/required_field.py

adds a basic graph data structure based on #405, #406

406 add graph structure

---

elasticai/creator/nn/quantized_grads/quantized_sgd.py
elasticai/creator/nn/quantized_grads/test_fxpmodel_loss_optim.py

Added Functionality for momentum and weight decay. 
Tests for momentum need improvement. Tests for weight decay are not existent.

feat(nn-qgrad): added momentum and weight decay

---

elasticai/creator/nn/fixed_point/conv1d/simulation_test.py
elasticai/creator/nn/fixed_point/linear/simulation_test.py
elasticai/creator/vhdl/shared_designs/mac/binary/_mac_test.py
elasticai/creator/vhdl/shared_designs/mac/binary/layer.py
elasticai/creator/vhdl/simulated_layer.py

Tests create files in the project root dir

---

tests/unit_tests/nn/fixed_point/linear/batch_normed_linear_test.py
tests/unit_tests/nn/fixed_point/linear/linear_test.py

Closing the branch after pull request

396 fixing batchnorm linearlayer

---

elasticai/creator/ir2vhdl.py

* blocked by #485 
Adds support for generating static files for
vhdl plugins. Static files will be loaded
from a "vhdl" folder.
Users only have to place the file in the
correct folder and declare its name in
the `meta.toml` file for the plugin.

feat(ir2vhdl): create static files from plugins

---

elasticai/creator/ir/__init__.py
elasticai/creator/ir/attribute.py
elasticai/creator/ir/attributes_descriptor.py
elasticai/creator/ir/graph.py
elasticai/creator/ir2vhdl/ir2vhdl.py

Makes ir related modules pass
mypy type checks.

refactor(ir): clean up type hints

---

devenv.nix

Mypy can discover a lot of bugs and
edge cases. We should do this in
CI.

ci: check types with mypy

---

.github/actions/prepare-devenv/action.yml
devenv.lock

chore(devenv): update devenv.lock

---

docs/creator/plugins/time_multiplexed_sequential.md
elasticai/creator_plugins/grouped_filter/__init__.py
elasticai/creator_plugins/time_multiplexed_sequential/README.md
elasticai/creator_plugins/time_multiplexed_sequential/meta.toml
elasticai/creator_plugins/time_multiplexed_sequential/src/__init__.py
elasticai/creator_plugins/time_multiplexed_sequential/src/_imports.py
elasticai/creator_plugins/time_multiplexed_sequential/src/node_protocol.py
elasticai/creator_plugins/time_multiplexed_sequential/tests/_imports.py
elasticai/creator_plugins/time_multiplexed_sequential/tests/high_level_network.py
elasticai/creator_plugins/time_multiplexed_sequential/tests/test_lower.py
elasticai/creator_plugins/time_multiplexed_sequential/tests/test_lower_fn_with_sliding_window_input.py
tach.toml

Supports to translate sequential networks made
up from simple filters to low-level IR describing
a time multiplexed version where each filter
kernel is instantiated once.

feat(ir2ir): add time multiplexed sequential plugin

---

elasticai/creator/graph/vf2/matching.py
tests/unit_tests/graph/rewrite_test.py
tests/unit_tests/graph/vf2/match_test.py

Change implementation slightly to
find all matches instead of only
non-overlapping matches.
Additionally, adhere to original vf2
paper with stricter feasibility conditions.

feat(graph): find all subgraph matches
